import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  Circle,
  ExternalLink,
  Eye,
  FileText,
  Home,
  Image,
  Laptop,
  Loader2,
  LogIn,
  LogOut,
  Mail,
  MessageCircle,
  MessageSquare,
  Moon,
  MoreHorizontal,
  Pencil,
  Plus,
  RefreshCw,
  Sun,
  Trash2,
  TrendingUp,
  User,
  UserPlus,
  ImageIcon,
  Users,
  X,
} from "lucide-react";

export interface IconProps extends Partial<React.SVGProps<SVGSVGElement>> {
  size?: string | number;
}

export type Icon = React.FC<IconProps>;

export const Icons = {
  fileText: FileText,
  users: Users,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  messageSquare: MessageSquare,
  trendingUp: TrendingUp,
  home: Home,
  refreshCw: RefreshCw,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  loader2: Loader2,
  image: Image,
  user: User,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  moon: Moon,
  sun: Sun,
  laptop: Laptop,
  login: LogIn,
  userPlus: UserPlus,
  logout: LogOut,
  plus: Plus,
  x: X,
  pencil: Pencil,
  messageCircle: MessageCircle,
  calendar: Calendar,
  externalLink: ExternalLink,
  trash2: Trash2,
  moreHorizontal: MoreHorizontal,
  eye: Eye,
  check: Check,
  circle: Circle,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  mail: Mail,
  imageIcon: ImageIcon,
};
